package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Anakoinwseis generated by hbm2java
 */
public class Anakoinwseis  implements java.io.Serializable {


     private Integer anakoinwsiId;
     private String titlos;
     private String perigrafi;
     private Date date;
     private String thematiki;

    public Anakoinwseis() {
    }

	
    public Anakoinwseis(String titlos, Date date) {
        this.titlos = titlos;
        this.date = date;
    }

    public Anakoinwseis(String titlos, String perigrafi, Date date, String thematiki) {
       this.titlos = titlos;
       this.perigrafi = perigrafi;
       this.date = date;
       this.thematiki = thematiki;
    }
   
    public Integer getAnakoinwsiId() {
        return this.anakoinwsiId;
    }
    
    public void setAnakoinwsiId(Integer anakoinwsiId) {
        this.anakoinwsiId = anakoinwsiId;
    }
    public String getTitlos() {
        return this.titlos;
    }
    
    public void setTitlos(String titlos) {
        this.titlos = titlos;
    }
    public String getPerigrafi() {
        return this.perigrafi;
    }
    
    public void setPerigrafi(String perigrafi) {
        this.perigrafi = perigrafi;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getThematiki() {
        return this.thematiki;
    }
    
    public void setThematiki(String thematiki) {
        this.thematiki = thematiki;
    }




}


