package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EidosDimosieusis generated by hbm2java
 */
public class EidosDimosieusis  implements java.io.Serializable {


     private Integer eidosId;
    private String eidos = "";
     private Set dimosieuseises = new HashSet(0);

    public EidosDimosieusis() {
    }

	
    public EidosDimosieusis(String eidos) {
        this.eidos = eidos;
    }
    public EidosDimosieusis(String eidos, Set dimosieuseises) {
       this.eidos = eidos;
       this.dimosieuseises = dimosieuseises;
    }
   
    public Integer getEidosId() {
        return this.eidosId;
    }
    
    public void setEidosId(Integer eidosId) {
        this.eidosId = eidosId;
    }
    public String getEidos() {
        return this.eidos;
    }
    
    public void setEidos(String eidos) {
        this.eidos = eidos;
    }
    public Set getDimosieuseises() {
        return this.dimosieuseises;
    }
    
    public void setDimosieuseises(Set dimosieuseises) {
        this.dimosieuseises = dimosieuseises;
    }




}


