package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Epipedo generated by hbm2java
 */
public class Epipedo  implements java.io.Serializable {


     private Integer epipedoId;
    private String epipedo = "";
     private Set mathimatas = new HashSet(0);

    public Epipedo() {
    }

	
    public Epipedo(String epipedo) {
        this.epipedo = epipedo;
    }
    public Epipedo(String epipedo, Set mathimatas) {
       this.epipedo = epipedo;
       this.mathimatas = mathimatas;
    }
   
    public Integer getEpipedoId() {
        return this.epipedoId;
    }
    
    public void setEpipedoId(Integer epipedoId) {
        this.epipedoId = epipedoId;
    }
    public String getEpipedo() {
        return this.epipedo;
    }
    
    public void setEpipedo(String epipedo) {
        this.epipedo = epipedo;
    }
    public Set getMathimatas() {
        return this.mathimatas;
    }
    
    public void setMathimatas(Set mathimatas) {
        this.mathimatas = mathimatas;
    }




}


