package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * KatastasiErgou generated by hbm2java
 */
public class KatastasiErgou  implements java.io.Serializable {


     private Integer katastasiId;
    private String katastasi = "";
     private Set ereynitikaErgas = new HashSet(0);

    public KatastasiErgou() {
    }

	
    public KatastasiErgou(String katastasi) {
        this.katastasi = katastasi;
    }
    public KatastasiErgou(String katastasi, Set ereynitikaErgas) {
       this.katastasi = katastasi;
       this.ereynitikaErgas = ereynitikaErgas;
    }
   
    public Integer getKatastasiId() {
        return this.katastasiId;
    }
    
    public void setKatastasiId(Integer katastasiId) {
        this.katastasiId = katastasiId;
    }
    public String getKatastasi() {
        return this.katastasi;
    }
    
    public void setKatastasi(String katastasi) {
        this.katastasi = katastasi;
    }
    public Set getEreynitikaErgas() {
        return this.ereynitikaErgas;
    }
    
    public void setEreynitikaErgas(Set ereynitikaErgas) {
        this.ereynitikaErgas = ereynitikaErgas;
    }




}


