package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Katigoria generated by hbm2java
 */
public class Katigoria  implements java.io.Serializable {


     private Integer katigoriaId;
     private String katigoria = "";
     private Set melois = new HashSet(0);

    public Katigoria() {
    }

	
    public Katigoria(String katigoria) {
        this.katigoria = katigoria;
    }
    public Katigoria(String katigoria, Set melois) {
       this.katigoria = katigoria;
       this.melois = melois;
    }
   
    public Integer getKatigoriaId() {
        return this.katigoriaId;
    }
    
    public void setKatigoriaId(Integer katigoriaId) {
        this.katigoriaId = katigoriaId;
    }
    public String getKatigoria() {
        return this.katigoria;
    }
    
    public void setKatigoria(String katigoria) {
        this.katigoria = katigoria;
    }
    public Set getMelois() {
        return this.melois;
    }
    
    public void setMelois(Set melois) {
        this.melois = melois;
    }




}


