package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mathimata generated by hbm2java
 */
public class Mathimata  implements java.io.Serializable {


     private Integer mathimataId;
    private Epipedo epipedo = new Epipedo();
    private String titlos = "";
    private Set melois = new HashSet(0);

    public Mathimata() {
    }

	
    public Mathimata(Epipedo epipedo, String titlos) {
        this.epipedo = epipedo;
        this.titlos = titlos;
    }

    public Mathimata(Epipedo epipedo, String titlos, Set melois) {
       this.epipedo = epipedo;
       this.titlos = titlos;
        this.melois = melois;
    }
   
    public Integer getMathimataId() {
        return this.mathimataId;
    }
    
    public void setMathimataId(Integer mathimataId) {
        this.mathimataId = mathimataId;
    }
    public Epipedo getEpipedo() {
        return this.epipedo;
    }
    
    public void setEpipedo(Epipedo epipedo) {
        this.epipedo = epipedo;
    }
    public String getTitlos() {
        return this.titlos;
    }
    
    public void setTitlos(String titlos) {
        this.titlos = titlos;
    }

    public Set getMelois() {
        return this.melois;
    }

    public void setMelois(Set melois) {
        this.melois = melois;
    }




}


