package model;




/**
 * MeloiDimosieuseisId generated by hbm2java
 */
public class MeloiDimosieuseisId  implements java.io.Serializable {


     private Integer melosId;
     private int dimosieusisId;

    public MeloiDimosieuseisId() {
    }

    public MeloiDimosieuseisId(Integer melosId, int dimosieusisId) {
       this.melosId = melosId;
       this.dimosieusisId = dimosieusisId;
    }
   
    public Integer getMelosId() {
        return this.melosId;
    }
    
    public void setMelosId(Integer melosId) {
        this.melosId = melosId;
    }
    public int getDimosieusisId() {
        return this.dimosieusisId;
    }
    
    public void setDimosieusisId(int dimosieusisId) {
        this.dimosieusisId = dimosieusisId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MeloiDimosieuseisId) ) return false;
		 MeloiDimosieuseisId castOther = ( MeloiDimosieuseisId ) other; 
         
		 return ( (this.getMelosId()==castOther.getMelosId()) || ( this.getMelosId()!=null && castOther.getMelosId()!=null && this.getMelosId().equals(castOther.getMelosId()) ) )
 && (this.getDimosieusisId()==castOther.getDimosieusisId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMelosId() == null ? 0 : this.getMelosId().hashCode() );
         result = 37 * result + this.getDimosieusisId();
         return result;
   }   


}


