package model;




/**
 * MeloiEreynitikaErgaId generated by hbm2java
 */
public class MeloiEreynitikaErgaId  implements java.io.Serializable {


     private Integer meloiId;
     private int ereynitikaId;

    public MeloiEreynitikaErgaId() {
    }

    public MeloiEreynitikaErgaId(Integer meloiId, int ereynitikaId) {
       this.meloiId = meloiId;
       this.ereynitikaId = ereynitikaId;
    }
   
    public Integer getMeloiId() {
        return this.meloiId;
    }
    
    public void setMeloiId(Integer meloiId) {
        this.meloiId = meloiId;
    }
    public int getEreynitikaId() {
        return this.ereynitikaId;
    }
    
    public void setEreynitikaId(int ereynitikaId) {
        this.ereynitikaId = ereynitikaId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        MeloiEreynitikaErgaId that = (MeloiEreynitikaErgaId) o;

        if (ereynitikaId != that.ereynitikaId) return false;
        return meloiId != null ? meloiId.equals(that.meloiId) : that.meloiId == null;

    }

    @Override
    public int hashCode() {
        int result = meloiId != null ? meloiId.hashCode() : 0;
        result = 31 * result + ereynitikaId;
        return result;
    }
}


