package model;




/**
 * MeloiEreynitikaErga generated by hbm2java
 */
public class MeloiEreynitikaErga  implements java.io.Serializable {


     private MeloiEreynitikaErgaId id;
     private EreynitikaErga ereynitikaErga;
     private Meloi meloi;

    public MeloiEreynitikaErga() {
    }

    public MeloiEreynitikaErga(MeloiEreynitikaErgaId id, EreynitikaErga ereynitikaErga, Meloi meloi) {
       this.id = id;
       this.ereynitikaErga = ereynitikaErga;
       this.meloi = meloi;
    }
   
    public MeloiEreynitikaErgaId getId() {
        return this.id;
    }
    
    public void setId(MeloiEreynitikaErgaId id) {
        this.id = id;
    }
    public EreynitikaErga getEreynitikaErga() {
        return this.ereynitikaErga;
    }
    
    public void setEreynitikaErga(EreynitikaErga ereynitikaErga) {
        this.ereynitikaErga = ereynitikaErga;
    }
    public Meloi getMeloi() {
        return this.meloi;
    }
    
    public void setMeloi(Meloi meloi) {
        this.meloi = meloi;
    }




}


