package model;




/**
 * MeloiDimosieuseis generated by hbm2java
 */
public class MeloiDimosieuseis  implements java.io.Serializable {


     private MeloiDimosieuseisId id;
     private Dimosieuseis dimosieuseis;
     private Meloi meloi;

    public MeloiDimosieuseis() {
    }

    public MeloiDimosieuseis(MeloiDimosieuseisId id, Dimosieuseis dimosieuseis, Meloi meloi) {
       this.id = id;
       this.dimosieuseis = dimosieuseis;
       this.meloi = meloi;
    }
   
    public MeloiDimosieuseisId getId() {
        return this.id;
    }
    
    public void setId(MeloiDimosieuseisId id) {
        this.id = id;
    }
    public Dimosieuseis getDimosieuseis() {
        return this.dimosieuseis;
    }
    
    public void setDimosieuseis(Dimosieuseis dimosieuseis) {
        this.dimosieuseis = dimosieuseis;
    }
    public Meloi getMeloi() {
        return this.meloi;
    }
    
    public void setMeloi(Meloi meloi) {
        this.meloi = meloi;
    }




}


