package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Meloi generated by hbm2java
 */
public class Meloi  implements java.io.Serializable {


     private Integer melosId;
     private Katigoria katigoria = new Katigoria();
    private String onoma = "";
    private String eponymo = "";
    private String webmail = "";
    private String shortCv = "";
    private String tilefono = "";
    private Set mathimatas = new HashSet(0);
    private Set dimosieuseises = new HashSet(0);
    private Set ereynitikaErgas = new HashSet(0);

    public Meloi() {
    }


    public Meloi(String onoma, String eponymo) {
        this.onoma = onoma;
        this.eponymo = eponymo;
    }

    public Meloi(Katigoria katigoria, String onoma, String eponymo, String webmail, String shortCv, String tilefono, Set mathimatas, Set dimosieuseises, Set ereynitikaErgas) {
       this.katigoria = katigoria;
       this.onoma = onoma;
       this.eponymo = eponymo;
       this.webmail = webmail;
       this.shortCv = shortCv;
        this.tilefono = tilefono;
        this.mathimatas = mathimatas;
        this.dimosieuseises = dimosieuseises;
        this.ereynitikaErgas = ereynitikaErgas;
    }
   
    public Integer getMelosId() {
        return this.melosId;
    }
    
    public void setMelosId(Integer melosId) {
        this.melosId = melosId;
    }
    public Katigoria getKatigoria() {
        return this.katigoria;
    }
    
    public void setKatigoria(Katigoria katigoria) {
        this.katigoria = katigoria;
    }
    public String getOnoma() {
        return this.onoma;
    }
    
    public void setOnoma(String onoma) {
        this.onoma = onoma;
    }
    public String getEponymo() {
        return this.eponymo;
    }
    
    public void setEponymo(String eponymo) {
        this.eponymo = eponymo;
    }
    public String getWebmail() {
        return this.webmail;
    }
    
    public void setWebmail(String webmail) {
        this.webmail = webmail;
    }
    public String getShortCv() {
        return this.shortCv;
    }
    
    public void setShortCv(String shortCv) {
        this.shortCv = shortCv;
    }

    public String getTilefono() {
        return this.tilefono;
    }

    public void setTilefono(String tilefono) {
        this.tilefono = tilefono;
    }

    public Set getMathimatas() {
        return this.mathimatas;
    }

    public void setMathimatas(Set mathimatas) {
        this.mathimatas = mathimatas;
    }

    public Set getDimosieuseises() {
        return this.dimosieuseises;
    }

    public void setDimosieuseises(Set dimosieuseises) {
        this.dimosieuseises = dimosieuseises;
    }

    public Set getEreynitikaErgas() {
        return this.ereynitikaErgas;
    }

    public void setEreynitikaErgas(Set ereynitikaErgas) {
        this.ereynitikaErgas = ereynitikaErgas;
    }


}


