package model;



/**
 * MeloiMathimataId generated by hbm2java
 */
public class MeloiMathimataId  implements java.io.Serializable {


     private Integer melosId;
     private int mathimaId;

    public MeloiMathimataId() {
    }

    public MeloiMathimataId(Integer melosId, int mathimaId) {
       this.melosId = melosId;
       this.mathimaId = mathimaId;
    }
   
    public Integer getMelosId() {
        return this.melosId;
    }
    
    public void setMelosId(Integer melosId) {
        this.melosId = melosId;
    }
    public int getMathimaId() {
        return this.mathimaId;
    }
    
    public void setMathimaId(int mathimaId) {
        this.mathimaId = mathimaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MeloiMathimataId) ) return false;
		 MeloiMathimataId castOther = ( MeloiMathimataId ) other; 
         
		 return ( (this.getMelosId()==castOther.getMelosId()) || ( this.getMelosId()!=null && castOther.getMelosId()!=null && this.getMelosId().equals(castOther.getMelosId()) ) )
 && (this.getMathimaId()==castOther.getMathimaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMelosId() == null ? 0 : this.getMelosId().hashCode() );
         result = 37 * result + this.getMathimaId();
         return result;
   }   


}


