package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ThematikiEnotita generated by hbm2java
 */
public class ThematikiEnotita  implements java.io.Serializable {


     private Integer thematikiId;
    private String titlos = "";
     private Set dimosieuseises = new HashSet(0);

    public ThematikiEnotita() {
    }

	
    public ThematikiEnotita(String titlos) {
        this.titlos = titlos;
    }
    public ThematikiEnotita(String titlos, Set dimosieuseises) {
       this.titlos = titlos;
       this.dimosieuseises = dimosieuseises;
    }
   
    public Integer getThematikiId() {
        return this.thematikiId;
    }
    
    public void setThematikiId(Integer thematikiId) {
        this.thematikiId = thematikiId;
    }
    public String getTitlos() {
        return this.titlos;
    }
    
    public void setTitlos(String titlos) {
        this.titlos = titlos;
    }
    public Set getDimosieuseises() {
        return this.dimosieuseises;
    }
    
    public void setDimosieuseises(Set dimosieuseises) {
        this.dimosieuseises = dimosieuseises;
    }




}


