package model;
// Generated May 28, 2013 6:44:39 PM by Hibernate Tools 3.2.1.GA



/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {


     private Integer userid;
     private String username;
     private String password;
     private String name;
     private String surname;

    public User() {
    }

    public User(String username, String password, String name, String surname) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.surname = surname;
    }
   
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }




}


