package model;
// Generated Dec 6, 2016 11:32:43 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userid;
    private String username = "";
    private String password = "";
    private boolean isAdmin = false;

    public Users() {
    }

    public Users(String username, String password, boolean isAdmin) {
       this.username = username;
       this.password = password;
       this.isAdmin = isAdmin;
    }
   
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }




}


